import type { Metadata } from "next";
import { Poppins,  Paytone_One} from "next/font/google";
import "./globals.css";
import React from 'react';

const poppins = Poppins({
  subsets: ["latin"],
  weight: '400',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
